apiVersion: ENC[AES256_GCM,data:ZL4=,iv:2art6RWCzC8YwkSSNcnyfmmwuImHooVVfpP9mjbjVv8=,tag:tuJVjL89quxOJ5N3RPdsUg==,type:str]
kind: ENC[AES256_GCM,data:uGsQMkAp,iv:34oU504AcgHnyO/XYc2K5eMFC4lg0yV/u1PplxzSt8Y=,tag:UseW6ZoFepJgQxjeK5UHZQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:kYMnuOQreTBFgYFzd5xs9g==,iv:JH/98Vaf18QYHWe9J/Q0VU7lXvVI3WPoGfLu5/2ZEY8=,tag:0jndrmuO4Oat2ghX6cy5aw==,type:str]
type: ENC[AES256_GCM,data:AW9X+0aY,iv:AjU7nOSimUyiA3YH50Z1HnP0h+cFxApj6Vi0dmEUhNQ=,tag:/BxaqTTsFvSUVbEjVkHRvA==,type:str]
data:
  DATABASE_URL: ENC[AES256_GCM,data:lZr0GbYiW8ZJ9C9Cs69OGMAsQoTpSn/iNpqXG3LRjXZ4UoJ6p8Y4jwDAsILg9xhAX5LFegOaLbYCIXFwaCPYRRSmyItkKP0Iyi6eDXlOu0NYJizQ8InjS/ZtBZl57uruFNkTIBK/SDTwj+SZlCyXeIuc2hfnpuKEyKBgzccp7sqn03W1RgtxTbUj5VmNdZ4/2KiQ+u/8ks2vGVOy5kImSYRxA5w=,iv:i9MIpRbqvpaPAzpa/TlHvjYiYsEHZvu8TiEOj/Tc4Us=,tag:d2HUFK7BVGHIhmqrvUYl/A==,type:str]
  LITELLM_API_KEY: ENC[AES256_GCM,data:H+Z6lY0OkdLxx9hcg2UIpUiPWWrqKOza1laQLHxjmNvXVzHp,iv:BNOMAbhcqohIL4nDPHVXPT4YhREG1oOCNK8Xwcc8W9U=,tag:1UQMpw/bjk2ai0dEb1Z6BA==,type:str]
  QDRANT_API_KEY: ""
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK1daWUY2cTB0eURDK0FO
        R25CZmFMcnJpRml0U20xNlgvSHhwYjM1dEdNCld6Zmo0UUt1SnBjek1lT2xsa1l2
        MThydE5WdGlHOXlENWQ5UHpQb2tOYjgKLS0tIGRDLzkxU2JXVDdtYjY2YXhnZ0Fy
        cG5HL2NHVjFjbFdDTktYRVhMcUJTcU0Kfw5t9MxypYsuq7hPsI5REZJlz/qmNyjX
        HZoI/pirc5La9pPF2waA68quftef3A9NoEa7qrw4vjDwL9OZDHuiJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T19:01:19Z"
  mac: ENC[AES256_GCM,data:GKz4PA2hAJERtVTnMq5HSPOrWTk3KTyfYNajewVPj/bXTo6ODDVzopvINgkc0yVww33kyMLXHXDU8tOa2AlFqjtRs+go5kzNgAT0f0DP/H4NCqwZPeHqdA0Y011ilXmm9yIRdheKcnnGvEPwmq51Yv5LvrrQSZyrNGYxuN+SyEI=,iv:ggiikT9r61LKyucR8V5qKRfcFfoYkLpi60tsEHwAhc0=,tag:lR44MNCQ0leBI6H7JLZcmA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
