apiVersion: ENC[AES256_GCM,data:ArQ=,iv:Nn4k+/5mGyWyr3BR/kMiiZAV1+OrRk08QO4V8dfTs3I=,tag:L1CQdQ2Cr6CyWbV421H+0Q==,type:str]
kind: ENC[AES256_GCM,data:c+1joZv4,iv:WQipVwiN+hg89uPmr6XjiTqCVggLcBgGk0vj0jk5bNw=,tag:h/qtM5I6EXJ+lIyM6jrDgw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:KzHUEoTiMPkqsf4MorXl,iv:oRJsEBQu5VxYoeH2nDBUl+pAGtOZjuOgb0vlTM+YutU=,tag:vp9G14dPMKjxbiKpIg8EjQ==,type:str]
type: ENC[AES256_GCM,data:NbGH2x06,iv:Ixaw7dBb7TrzDDfihyqvFGVXAsJHw63COujmiqC3wKU=,tag:bJEh5x+cVMzgfgKvnx6otg==,type:str]
data:
  DB_PASSWORD: ENC[AES256_GCM,data:YOr/LGW8JwLWOetXQDt85a/PHXOhpqF7,iv:SFGF5F6U5hejeiVHYCpOa6bjL+0Hm8yevqwIW39VK1g=,tag:8Ym75MzU9X97rVTUUDsNdA==,type:str]
  DB_USER: ENC[AES256_GCM,data:ruRz0cHTX3Q=,iv:6l/A3t5v6fGyrCUJ5T8EyHGkBS0aLldTckn5LETgiG8=,tag:XWB6S1vLwuZ2wdwxJGjLwg==,type:str]
  EMBEDDING_API_KEY: ENC[AES256_GCM,data:9Ufp2AuS6lgMTwvwIIGI5dqVKwl9I8HvspvKvge4/90jOZod,iv:XU1O99Q6KqOTtO7ly2AjAufRbpidntXztOH92pmEIWQ=,tag:WJGtdhXZEeNjtTgcjDeb9g==,type:str]
  QDRANT_API_KEY: ""
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UG5KWWpRSGp3VzdCdGpW
        Lyt4bVl3ZWFqYndqcVlxODg3MDNxMWlXaURBCjdSZFNBK21MVkxpcXRBM3ZNS2Mr
        c1ZYeVltZFFFTjFmUWlnRkU3V2I4ZncKLS0tIFhzbWR6UnpTWFZiSG4rZk5zU2dm
        ZW5QK1pNSW1LYmRabkV1elZQcGVValEK99fEW2oV2BUIJwvr67ISJez0IWQMmhVX
        q21fzCdbSuKfA7f58oDu8pJ9INw+juzfsl6F51eVtIz5rxMp6O94vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T17:40:43Z"
  mac: ENC[AES256_GCM,data:nc7IGpFfLTAVyL2sZqocTkG4Ez+ZRUPmxU+yFKhRR582yQKZnG/nsQzp6ost/+KiLF8Oe6gM9GjEvlbPpng1Xa6CUmDx3qeIECDiNNoGBo3diYLlutTnSPZHee7j7ehWbxJnpYVIRoCnsLHxm6U5QgWfhTnDyUJ8G/NSfhftfrM=,iv:mWhNDPp7rzc2GEYkR4CAfgc42qaDcSrp3U0kfRvHPdA=,tag:90DCFvUUoKao9onpGfyL3w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
