apiVersion: ENC[AES256_GCM,data:nWk=,iv:x5OpeQD7xbfrB5mURrrKULP5G7MN2hHZM2dzdCzSKKw=,tag:uNfKMzr9FcpDiRJxl2BjBA==,type:str]
kind: ENC[AES256_GCM,data:CQ1iuzgF,iv:hPglNbxo6SpVoq0T9Z0+mBIKlyB4XdddaguMrhAHClU=,tag:jNBZXeDXZStbpi/yGBqN5Q==,type:str]
metadata:
  name: ENC[AES256_GCM,data:IweZVvaYrLeW8kfYi9ca,iv:tdFrfWemxUTH55vNILDmHiXFKvUc+gzDWG5FmDja//A=,tag:2vt/9+LWyIDoLhC7kjW77A==,type:str]
type: ENC[AES256_GCM,data:nWhPso5J,iv:wVbvSN5MKYj+9Ldek9o5NR69G+UQggkP+I6jtElODUw=,tag:WczmGRCdZQSb1/Fh4F9/Wg==,type:str]
data:
  DB_PASSWORD: ENC[AES256_GCM,data:iAJryHslBIPs7iDVIAIXmx0ErkhbNhYB,iv:Oyt16PkCauqX8u3/GbyuTtn984Q2R9+aSD01t7TVMk0=,tag:EaLJXlvKS8IFxSO+iPctcA==,type:str]
  DB_USER: ENC[AES256_GCM,data:Fe7iCoy9qFI=,iv:QNbc9rVnH1NsSZRacxpur5h27maSp0ta4gnR4pBIW6M=,tag:rbs9w9HmExzH31PJtQoM0g==,type:str]
  EMBEDDING_API_KEY: ENC[AES256_GCM,data:QlGnrPkJK33HRUTR6ey/4o6tR6Q4SEoF3naAixiP3WbG0npS,iv:KAPQgtZLo/3gedl4WRY3200ZO9RAUWG7VhGHcAsYn68=,tag:oZDs3kK7mRyIrbxMyOghoQ==,type:str]
  QDRANT_API_KEY: ""
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ2lKV29QUmlBZUMwc2dK
        c0VnQlJoYUc4YWNJRncyZWZiNi9yd2lNNlhjCmNmNlBvVVl2enhnMndrVU9uL3B1
        ZmlaZS9wa3B4YmloTHFnZzc0SkM1UTgKLS0tIG1pZlA1Vzg0bUZlOHhlWW00Vyt1
        ZGlBVW05ajlkT0oxdDdQbUtPc1lCWnMK870uSTyZbRdU1Nhr400F30uWWY+l8su9
        5ah5MrH/P25KjLM+ydV2srDgaSC+RxdtLCTksqaOQ5jaUx0GIqBPew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T19:01:19Z"
  mac: ENC[AES256_GCM,data:g6Qbh/PzAud2TqzWTjij/a9BOL9XZRxf5FB4e64lzo7Q4Es4b5+pDcqbuQX+29cbVN9HxPSYZw00AmRcn8Hg2RCUvVQ4oqj61yUdm9Ce77BKhMxKBJicpH8QsnXE+UWloO/O3Hx/cB2GrjcqjDdznTZwh4b6kF0JBeiW74qgCR4=,iv:TkVteveUaWajSZ5dRI2LkAX3xY8PZo12bVhpPecpups=,tag:jC33x444N1cjYLoCjOxMsw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
