apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  source:
    repoURL: git@github.com:244sinfall/darkmoon-cluster.git
    targetRevision: HEAD
    path: apps/litellm/overlays/shared
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-provider
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: litellm-postgres
      namespace: llm-provider
      jsonPointers:
        - /metadata/labels/app.kubernetes.io~1instance
        - /spec/template/metadata/creationTimestamp
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/securityContext
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
        - /spec/volumeClaimTemplates/0/status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
