apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://kvaps.github.io/charts
    chart: nfs-server-provisioner
    targetRevision: 1.8.0
    helm:
      releaseName: nfs-storage
      values: |
        persistence:
          enabled: true
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 30Gi
        storageClass:
          create: true
          name: nfs-shared
          defaultClass: false
          reclaimPolicy: Delete
        nodeSelector:
          kubernetes.io/hostname: control-plane.dm
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-storage
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: nfs-storage-nfs-server-provisioner
      jsonPointers:
        - /metadata/labels/app.kubernetes.io~1instance
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/template/metadata/creationTimestamp
        - /spec/template/spec/containers/0/env/0/valueFrom/fieldRef/apiVersion
        - /spec/template/spec/containers/0/env/2/valueFrom/fieldRef/apiVersion
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/containers/0/terminationMessagePath
        - /spec/template/spec/containers/0/terminationMessagePolicy
        - /spec/template/spec/dnsPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/securityContext
        - /spec/updateStrategy
        - /spec/template/spec/serviceAccount
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
        - /spec/volumeClaimTemplates/0/spec/volumeMode
        - /spec/volumeClaimTemplates/0/status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
