apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-secrets-vpn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: git@github.com:244sinfall/darkmoon-cluster.git
    targetRevision: HEAD
    path: apps/_shared/overlays/vpn
  destination:
    server: https://kubernetes.default.svc
    namespace: vpn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
