apiVersion: v1
kind: Service
metadata:
  name: dev-world-bnetserver
  labels:
    app.kubernetes.io/name: dev-world-bnetserver
    app.kubernetes.io/part-of: game-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dev-world-bnetserver
    app.kubernetes.io/part-of: game-server
  ports:
    - name: tcp
      port: 1119
      targetPort: 1119
      protocol: TCP
    - name: rest
      port: 8081
      targetPort: 8081
      protocol: TCP
