apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: game-server-dev-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/game-server-config.dev.enc.yaml
  - ../../secrets/dev-world-mariadb.dev.enc.yaml
