apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-world-cameras-pvc
  labels:
    app.kubernetes.io/name: dev-world-worldserver
    app.kubernetes.io/part-of: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-world-dbc-pvc
  labels:
    app.kubernetes.io/name: dev-world-worldserver
    app.kubernetes.io/part-of: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-world-gt-pvc
  labels:
    app.kubernetes.io/name: dev-world-worldserver
    app.kubernetes.io/part-of: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-world-maps-pvc
  labels:
    app.kubernetes.io/name: dev-world-worldserver
    app.kubernetes.io/part-of: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-world-vmaps-pvc
  labels:
    app.kubernetes.io/name: dev-world-worldserver
    app.kubernetes.io/part-of: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
