apiVersion: v1
kind: Service
metadata:
  name: dm-agent
  labels:
    app.kubernetes.io/name: dm-agent
    app.kubernetes.io/part-of: ml
spec:
  type: ClusterIP # Internal-only service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dm-agent
    app.kubernetes.io/part-of: ml
---
apiVersion: v1
kind: Service
metadata:
  name: cross-encoder-reranker
  labels:
    app.kubernetes.io/name: cross-encoder-reranker
    app.kubernetes.io/part-of: ml
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cross-encoder-reranker
    app.kubernetes.io/part-of: ml
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: ml
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: ml
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
