apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: backend-dev-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/backend-appsettings.dev.enc.yaml
  - ../../secrets/backend-env.dev.enc.yaml
