apiVersion: ENC[AES256_GCM,data:JHg=,iv:ChUxAiIgzgVwSlDRPmmFhHyHjtdzNW4m49UebovW6O8=,tag:eKsfz0erxmTAVAHYkSF6tw==,type:str]
kind: ENC[AES256_GCM,data:X2SS4yvg,iv:ulbXUeCEgwvOwu/pEe00h73xO+eM23n77XJBIF0YRFs=,tag:Q2qjR3/DBHWYMEOqJC5+EA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:D+0fmmQgSjpaMIc=,iv:KJdMbL+Lv9XW7VC4s8kPO1rJRonNTJsHakAmEgq6iDs=,tag:Fyb/kw11TKuxMyaVZZ0e1g==,type:str]
type: ENC[AES256_GCM,data:14XkGHRD,iv:IQghOjMXVlTAcHbB7RQ3KxmcL5I1t8xqGj9jCHP3TQc=,tag:xeka4CWQSeuwiHDQr1tTMg==,type:str]
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:BKBZW6rlE6ZKjpFyVHaPnqymdueGMVfPUMHMp72vIB/+Yn1GEfJc0X15J1TzOVr8Leo684GocO8Hw7HJao50W0S1aWVlVAa5qnOCCXL/7iMAvUfZ8W+P700bDbWij1RwuJnmuPoIbA==,iv:embYMsxEbDOulRP1HUPCBfbeIFGKGLDppWZcG6Lvr8E=,tag:K7nn4xuU8DbJWkH3Nl8mFQ==,type:str]
  UI_USERNAME: ENC[AES256_GCM,data:r8S+Ez8=,iv:camnOjrXi4lT8vfc4ILnuLLvEVnd2BtS336E/uqAjfk=,tag:SwQvKnAFK4CV5sLbucO0aw==,type:str]
  UI_PASSWORD: ENC[AES256_GCM,data:3q303Zzd4mqdnoK6KZFkv26cpxY=,iv:735AmeyhArPBh/8CTlx78kQ3w9ewlq8GelbncJaIbxw=,tag:2cvJqbQo6vpNk0+rhvF/7w==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:c1Cksx+rHwMHt+ct0VsJa8ndsZmKz+D9nTLfN88+lDKrnBoiWUZbuxkUZarTIGBuZ6tvZgAidsWtTag6kTgb2fVKOo6FAWic1EFWDAnIAuGFetE/tgHHHTBW0+FLXhiiiZvU7VDqIhjei0X/YRphHrWRKl4D3c4busHnY/QY74iMOVg=,iv:esHK52mji9ZAyUUo7Ug9Z7JfxBLEUXSTAD2GMMC03zE=,tag:B5mFM4s9gI5/UWPyJxGNGg==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:Ht1rVTR0Hi0Vb287Iku/TOHO+/SCKRnPX5DBYZeEsni6mcXZ62wfmodbVgvN0CO84ZXoUNZnaNHTttTO8OLzXULHI55pHy2IN3nPvU0mKo/lfqKoIY1SXi1tyaSoT9exuAJr90mfVq35YKOKuW7DwDc/Hz6iJp6BMi3axnX7nJ4pyck=,iv:MOGW37wDjtCOB+cew9bmthGys3W5WN7zza52TXUbWfk=,tag:MVlrGYkUkwMBI1YlfXqHaw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:xA4inovFbSZ7D+ttNvDocgrceWI=,iv:/xSmw9kjROrm7PGXwO+LT2ns39Me7+TcAgXKJB28LIE=,tag:GeTqZ8FXhog97tnZ3To8Aw==,type:str]
  PROXY_BASE_URL: ENC[AES256_GCM,data:Lrakh5y6Cb72gu14LlQOEq5lUwtNrNhrbw==,iv:/QDBnUconeMDXOfwTURTU8/ZQMgRGwBYnMnPdsBbA6g=,tag:5/2tNUmbuSFmHow0gAuqUw==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN0NPNmVSZVJ3WVMwZDBh
        dzZRRlI2MVFRSHVxWngwQ1B4RE1uMEloQm5BCklEWUhwV0hDcnZYdjJCQzdURW5x
        aHNhN2VlcVdGZmxwTG95dUFrZnFPa3MKLS0tIFExRXdTNTFYZENKZkc5RXhoc1JL
        VEtXRjlFOHNrcXFzdmNoTHhySG9OQlkKJzLLrXYkHzvVTQ2J8Xv37+2L0tnIPe/V
        Rz2j/v1Aue3djv02EnxnyxjFZSgCWSm1Jsz1mdWrkXguZ0xoWuIAKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T13:08:05Z"
  mac: ENC[AES256_GCM,data:WO3Rsd6LkSGOrQxLHcd+zP3WBc+71OS2nzlRasLMDKKQ751JmVnO2mD/zlfYmRqWbmpVh/VWojVqynH912b99SOuTLE9WoRb/9MuyZKWGvTs9xuKLY8+hJII5/aSBSnYjhy4ydtbpZ18IQ7mPzs84khZCGleDU/qG3nwgqQxV78=,iv:ReiipyCoRHqxin+28JOjekoCpytOHIKRzgFcaRKalXo=,tag:JrGKB8EquZNjkIxKyCl2Ug==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
