apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml
resources:
  - ../../base
  - configmap.yaml
generators:
  - secret-generator.yaml
replicas:
  - name: qdrant
    count: 1
  - name: dm-agent
    count: 1
  - name: cross-encoder-reranker
    count: 1
