apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ml-shared-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/dm-agent-secrets.enc.yaml
  - ../../secrets/indexer-secrets.enc.yaml
