apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-integrations
resources:
  - ../../base
  - configmaps.yaml
  - ingress.yaml
  - pvc.yaml
generators:
  - secret-generator.yaml
