apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: integrations-prod-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/integrations-files.prod.enc.yaml
  - ../../secrets/integrations-env.prod.enc.yaml
