apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev.yaml
  - local-path-storage.yaml
  - llm-provider.yaml
  - nfs-storage.yaml
  - stage.yaml
  - prod.yaml
  - playground.yaml
  - registry.yaml
  - prod-integrations.yaml
