apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - ingress.yaml
  - ru-ingress.yaml
  - rabbitmq-certificates.yaml
generators:
  - secret-generator.yaml
replicas:
  - name: api-gateway-service-dotnet-service
    count: 1
patches:
  - path: statefulsets-prod-patch.yaml
