apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: backend-prod-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/backend-appsettings.prod.enc.yaml
  - ../../secrets/backend-env.prod.enc.yaml
