apiVersion: ENC[AES256_GCM,data:XRk=,iv:C8f5ffucBV8RiHF7H390LaUJRbYoWnakF5/JbA6ObyM=,tag:cBCxpThjrwypn3gA7zVavA==,type:str]
kind: ENC[AES256_GCM,data:PC4Jsrhb,iv:3jT8d3druhfadyktuN61fwObH8kp23yAHU5Mj4ULX0M=,tag:Ny3aMMqAIRYxcMMSI2tISg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:MDNa44AOBEVykxRNBzst6ZON,iv:50VyFzIyp+zNZTJYfQDz3NZja3A4Mwgq5fUVkomkYPY=,tag:Bz9rWzJCp4Qitf8XkEodFQ==,type:str]
  namespace: ENC[AES256_GCM,data:mmfZemRqOBvG,iv:U0D0cVHaXrK63kpeY/DQIfG8Sc2UDVXtGBV/qQAi3Fs=,tag:DumBeInzZUjKKisdoaeLUA==,type:str]
type: ENC[AES256_GCM,data:ls4DTmvl,iv:16gc8hvD0EvbZsFwv6C3nr8f4d70IM50Vhyd9udZyxA=,tag:C/z/RZvMRPhpvHPz5Hl0Ig==,type:str]
stringData:
  demoToken: ENC[AES256_GCM,data:yMfFSL3Q3Azv,iv:KJ5e8xDxyBxgUgldpG4NcSTG65An/E7GIFlwD39WwhU=,tag:yLQxmeRBHeNxaL7n5CnCrw==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNWd4TlVROGJseXVkV1pX
        bFAxTXBiR25rbEVHQk5BY0FqMEE3UmxpS2swCkFEZHBuQ3Z2bm9RdkV2b1pZd1Zr
        ZWl1RVJ0Vzk3WHZvMklRNW1xbEF4SjgKLS0tIFo2TUR0cHJFYUU4dHVsMnVaK1NM
        aXk3LzNIdWxCZ1FoRUVEZlB2ZVhha1kKwt83+SBBtznz3ht3eF9mOgYWGBpPcWrq
        UAXrU+5NVlF21so/YtC/5YuLvtQm2H+KXetcBN+BDbYqLdwM9QBdFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T11:44:18Z"
  mac: ENC[AES256_GCM,data:GxstF5exDPR0obMppW65MPEKCBfea/8CH4pJ5xnm0JMu4tfMWEDlvamdni/6xyP4GLe4mvb9QhKlMZZfoFTWb1kJ6LAheXqzgFsgTmDA2IhZ4VwUtjj0Ve37xvUDC0rKdFIPao4FPCFvcODtDvVAzOZcTBdkExg6CslEVQO/ln0=,iv:2P0etSRAjZIP9hQs7Xu092fVUBr1+5G1T+nYTvPMWE8=,tag:pAXUm9jQCnj2Rw0brgL+zw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
