---
apiVersion: v1
kind: Service
metadata:
  name: backend-postgres
  labels:
    app.kubernetes.io/name: backend-postgres
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: backend-postgres
    app.kubernetes.io/part-of: backend
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app.kubernetes.io/name: redis-master
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-master
    app.kubernetes.io/part-of: backend
  ports:
  - name: redis
    port: 6379
    targetPort: http
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: backend
  ports:
  - name: amqps
    port: 5671
    targetPort: amqps
    protocol: TCP
