apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps.yaml
  - statefulsets.yaml
  - infrastructure-services.yaml
  - dotnet-deployments.yaml
  - dotnet-services.yaml
  - runtime-deployments.yaml
  - runtime-services.yaml
  - cronjobs.yaml
