apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: launcher-service-artifacts-pvc
  labels:
    app.kubernetes.io/name: launcher-service-dotnet-service
    app.kubernetes.io/part-of: backend
    app.kubernetes.io/component: launcher-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-shared
