apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: litellm-shared-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/litellm-config.shared.enc.yaml
  - ../../secrets/litellm-env.shared.enc.yaml
