apiVersion: ENC[AES256_GCM,data:2aA=,iv:/z4mnqTJC3ixZqNWMXp9t4R6VR396PtDXlmZxuu0iKA=,tag:INrT0KjShiRvardbj4BSyg==,type:str]
data:
  mariadb-password: ENC[AES256_GCM,data:OgP5sw/iF0xVOSNBOcFXluDmlN6kq77+gNdZu1zhq3IUudyYlIsK7PFksNiIHgNGHno7viMJCmlGNvmyA9QKooT2v7a8YHszONb65JJvZSJqvOnyGP8pKQ==,iv:RzhfWJbHHuxBdRE/gGwse0YlVOs736x6XEr6LxkHb4k=,tag:A3YI6yg89MfkecSboIYxCw==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:O1XTTFGC2CUD/iwNHiP81kul1flofaxtPJBY9Rie+hxr0wtt3ncy85f6F/DTachaCZj5NUGrs2jPPnHShxb/DehG9ZfzFevJXZbz+306kGq+30u9QxQS+Q==,iv:Mi34YMIXQtRcWAzADE8AHJFcKTQRhEfxcj1engzCAQM=,tag:IFKBsPNZP/99L67094CAvw==,type:str]
kind: ENC[AES256_GCM,data:8CwXJv6U,iv:N3RUBy0vXts3rTcmFL+jP3NJduUGGE7GfNlCl8Y6yhI=,tag:REgjcX1He/l/d70BNzn8xA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:gZzG2F1TPwvYOTqOoPCnKkC+t4iPtw==,iv:O2dUxVdb0aEaQ3BesVbUNqWqo7KjvyRgCG27VCoIU+Y=,tag:oAMd7B0oS7yxgzVGw5RYXQ==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteTkzdDZMRFZDT2R3S3R5
        RmQ2Yjl6bnFxdzBTUnpzMmpRVnVWU3dYRXhBClYxREhVQVhCd1k0UlExUHFhRVl1
        M2ZXRXUzODlpRGoySlV3bkJCcFhVZTAKLS0tIDRhblN0TEMvSGovWmNwaVUzQjN2
        dDg3SGVtM0dwMHB1QlhmdUNmRVlYSGcKFEnmhit6tE/EKHPcnRMlrNbV8OEH3g10
        8/EMILTOHlbuTyjGumEq9aFqg68ZC5ei64FIpeRZ8J9+Xhz9pn/S4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T21:19:15Z"
  mac: ENC[AES256_GCM,data:xtyAar+BYJ9wF6ZIvA+oteWqMNtp0E6SnaKnntHgYVX3iO8VIKrmtxUOcPsYGKxJDpgScWd7pKIBdFIl5RLbWB6vpixRXPdhoT2UB4LoUN8TWoPG1gm+/eoVtPRATB5z6BQFzG+TozfNcw81Wqa8WxWK3Emeumx1StLY3zv9VF4=,iv:1u/kNqZ+CIDciyK+yeUkLdI00UN+uk/VUs7rZdOliwg=,tag:fYHqj+m4pekzUZFRHprl3A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
