apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: site-dev-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/site-config.dev.enc.yaml
  - ../../secrets/site-mysql.dev.enc.yaml
