apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project-platform.yaml
  - applications/cert-manager.yaml
  - applications/cluster-config.yaml
  - applications/ingress-nginx.yaml
