apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: shared-image-pull-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../secrets/registry-pull-secret.enc.yaml
