apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-default
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-rest-api
      app.kubernetes.io/component: default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-rest-api
        app.kubernetes.io/part-of: vpn
        app.kubernetes.io/component: default
    spec:
      containers:
        - name: wg-rest-api
          image: leonovk/wg-rest-api
          env:
            - name: AUTH_DIGEST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpn-auth-tokens
                  key: default
            - name: ENVIRONMENT
              value: "production"
            - name: WG_PRE_UP
              value: sysctl net.ipv4.ip_forward=1
            - name: CONNECTING_CLIENT_LIMIT
              value: "16"
            - name: CONNECTING_CLIENT_LIMIT_6
              value: "112"
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
            - name: api
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wg-config
          securityContext:
            privileged: true
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wg-rest-pvc-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-internal
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-rest-api
      app.kubernetes.io/component: internal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-rest-api
        app.kubernetes.io/part-of: vpn
        app.kubernetes.io/component: internal
    spec:
      containers:
        - name: wg-rest-api
          image: leonovk/wg-rest-api
          env:
            - name: AUTH_DIGEST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpn-auth-tokens
                  key: internal
            - name: ENVIRONMENT
              value: "production"
            - name: WG_PRE_UP
              value: sysctl net.ipv4.ip_forward=1
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
            - name: api
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wg-config
          securityContext:
            privileged: true
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wg-rest-pvc-internal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-external
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-rest-api
      app.kubernetes.io/component: external
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-rest-api
        app.kubernetes.io/part-of: vpn
        app.kubernetes.io/component: external
    spec:
      containers:
        - name: wg-rest-api
          image: leonovk/wg-rest-api
          env:
            - name: AUTH_DIGEST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpn-auth-tokens
                  key: external
            - name: ENVIRONMENT
              value: "production"
            - name: WG_ALLOWED_IPS
              value: "0.0.0.0/0"
            - name: WG_DEFAULT_DNS
              value: "1.1.1.1, 8.8.8.8"
            - name: WG_PRE_UP
              value: sysctl net.ipv4.ip_forward=1
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
            - name: api
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wg-config
          securityContext:
            privileged: true
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wg-rest-pvc-external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amnezia-wg-easy
  labels:
    app.kubernetes.io/name: amnezia-wg-easy
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: amnezia
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: amnezia-wg-easy
      app.kubernetes.io/component: amnezia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: amnezia-wg-easy
        app.kubernetes.io/part-of: vpn
        app.kubernetes.io/component: amnezia
    spec:
      containers:
        - name: amnezia-wg-easy
          image: ghcr.io/w0rng/amnezia-wg-easy:14
          imagePullPolicy: Always
          env:
            - name: PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: vpn-auth-tokens
                  key: externalAWG
            - name: LANG
              value: "en"
            - name: PORT
              value: "51821"
            - name: WG_PORT
              value: "51820"
            - name: WG_CONFIG_PORT
              value: "31823"
            - name: WG_ALLOWED_IPS
              value: "0.0.0.0/0"
            - name: WG_DEFAULT_DNS
              value: "1.1.1.1, 8.8.8.8"
            - name: WG_PRE_UP
              value: "sysctl -w net.ipv4.ip_forward=1; sysctl -w net.ipv4.conf.all.src_valid_mark=1"
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
            - name: ui
              containerPort: 51821
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/wireguard
              name: amnezia-wg-config
            - mountPath: /dev/net/tun
              name: dev-net-tun
          securityContext:
            privileged: true
      volumes:
        - name: amnezia-wg-config
          persistentVolumeClaim:
            claimName: amnezia-wg-easy-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amnezia-wg-easy-default
  labels:
    app.kubernetes.io/name: amnezia-wg-easy
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: amnezia-default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: amnezia-wg-easy
      app.kubernetes.io/component: amnezia-default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: amnezia-wg-easy
        app.kubernetes.io/part-of: vpn
        app.kubernetes.io/component: amnezia-default
    spec:
      containers:
        - name: amnezia-wg-easy
          image: registryv2.rp-wow.ru/amnezia-wg-easy:14
          imagePullPolicy: Always
          env:
            - name: PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: vpn-auth-tokens
                  key: defaultAWG
            - name: LANG
              value: "en"
            - name: PORT
              value: "51821"
            - name: WG_PORT
              value: "51820"
            - name: WG_CONFIG_PORT
              value: "31824"
            - name: WG_DEFAULT_ADDRESS
              value: "10.8.0.0/16"
            - name: WG_DEFAULT_DNS
              value: "1.1.1.1, 8.8.8.8"
            - name: WG_ALLOWED_IPS
              value: "65.108.101.119/32, 135.125.233.102/32, 5.39.76.31/32"
            - name: WG_PRE_UP
              value: "sysctl -w net.ipv4.ip_forward=1; sysctl -w net.ipv4.conf.all.src_valid_mark=1"
          ports:
            - name: wireguard
              containerPort: 51820
              protocol: UDP
            - name: ui
              containerPort: 51821
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/wireguard
              name: amnezia-wg-config
            - mountPath: /dev/net/tun
              name: dev-net-tun
          securityContext:
            privileged: true
      volumes:
        - name: amnezia-wg-config
          persistentVolumeClaim:
            claimName: amnezia-wg-easy-default-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
