apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-rest-pvc-default
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-rest-pvc-internal
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-rest-pvc-external
  labels:
    app.kubernetes.io/name: wg-rest-api
    app.kubernetes.io/part-of: vpn
    app.kubernetes.io/component: external
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
