apiVersion: v1
kind: Service
metadata:
  name: ru-proxy
  labels:
    app.kubernetes.io/name: ru-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ru-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
