apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-default
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "176.12.77.213"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-internal
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "176.12.77.213"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-external
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "176.12.77.213"
