apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-default
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-internal
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-external
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: control-plane.dm
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
