apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-default
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: dmvpn
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amnezia-wg-easy
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker.dm
      containers:
        - name: amnezia-wg-easy
          env:
            - name: WG_HOST
              value: "176.12.77.212"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-internal
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: dmvpn
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-rest-api-external
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: dmvpn
      containers:
        - name: wg-rest-api
          env:
            - name: WG_HOST
              value: "212.74.231.117"
