apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: vpn-dev-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/vpn-auth-tokens.dev.enc.yaml
  - ../../secrets/openvpn-external-certs.dev.enc.yaml
