apiVersion: ENC[AES256_GCM,data:SqM=,iv:W0YrKzqVylw+XA/JXt4+mDadxnIhrDV3c0nRkIpvx7Q=,tag:3dlzE8nIrc4BU+T5zd8Kwg==,type:str]
kind: ENC[AES256_GCM,data:d4n2QOr5,iv:D3/hpcBAwO1sK3IRt0TWBLgt6JOJeVe31U3JUyyvz6o=,tag:2v2jgMVZJIzWTPtwP3tVQg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:Z7CXPxMZ52X4ox1VBAlcyBygVfA=,iv:e6pUL4DCObQq9RwSOJavsrS1HOCN67nJORbiEM/IZIk=,tag:ODp5kL3jFW7zPr6XGOKr9g==,type:str]
  namespace: ENC[AES256_GCM,data:HFvxIm6EiXnDdegt,iv:iiSshsnmkFVjXEZrp3zni+XBtpnOguRWyccRmM2VkmY=,tag:SP9s6z6Bzj8BiXRMRLRz2Q==,type:str]
type: ENC[AES256_GCM,data:X5WheuQp,iv:1eYffhVNl18fQTAe+qYQiVzvEqNx2SXFw/r+tBb8OEg=,tag:aWf3BvXBpgo2YmOQlg7DTQ==,type:str]
stringData:
  api-token: ENC[AES256_GCM,data:d5AEp6MjpGby1HMzanfMQ+BSEj8TeC3xZMu33WZxscwVZKfrRsMGFNd5OF88qrJcRB/zoIQ=,iv:vqaKZZKIJg9PuFmccJBUvzDUmQanHlIcH6u6aAF3FE0=,tag:m3eeUqshLSLJVAydaxF/JA==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZmUvM2NPbnA2K1owd0wy
        enNOeDVzdFJXUkpVdnd4VU11SlMzUmlXN0dRCjk4SWg2dWJiRmtUbUZxMFhlQ092
        Z0dVeVBpbEswcU1BcmpBcXR0QitqMWMKLS0tIEtUNjA0SjdiVVppVGdSazJ6bGpj
        c1pTQ3krajdMbnhmbE5CZmZaeDh3SFEKb9oBQ0s92eFb6zA0/OZYGkyc8Se3Bhlk
        AJjmGbsOuaH4nmwe8XApuhqMW7PBJ6hfo92wbsDGB85RRzdGY4e9gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T16:13:24Z"
  mac: ENC[AES256_GCM,data:D/P1VNTOvrL7GhpTpOOh1nB/7yH3veqS1e4z8LP8z3NDwJoqtSfiKNFSnaR3C+1F3KAuO5l+KtAN8c+Gnji6T2zniM5Sublx4V7865GvPbxjKGn3NmJDdUXbztBsvYEO4rlfLnnLKhjurQrPqN5UXHLDhrrfnWy1x8yxRvRiA/s=,iv:DdSxs2ZSgYcw227A9PlzEZoL0B++KiyWOfD2ot2+5OY=,tag:Gn1HEvVW7rhjxT8oeffUQQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
