apiVersion: ENC[AES256_GCM,data:teE=,iv:AMLqFnMGRJ2hYexoZ8VfUXuZS6eR5uEaEL2we20ccAc=,tag:bT1DM92efjOhillD6ZCTGw==,type:str]
kind: ENC[AES256_GCM,data:eZ888BJp,iv:+9zoBoaalczbFzK0jMfEfxS9E5fjXxwH5DRxmp68VdQ=,tag:6auLSiL6V+E6qMJI2MlpkA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:QG6Q1zwwjPokU9Zg9EPKrso+Mw==,iv:KSAYLdNq48p6JS8Lpafrh4iJM/Id0VM1GPcQh4B37gc=,tag:Sdrv7gMPxY3LHlUVzwjZvQ==,type:str]
  namespace: ENC[AES256_GCM,data:M1gAwoUtLu4=,iv:4CtWzI1g6TOgJez1koCY3Qrk7/55M79kPZWJrIMHbC0=,tag:4h99riqmBv+Vvs2r9F0PEA==,type:str]
type: ENC[AES256_GCM,data:RcuWH5pY,iv:1M6NWv0hJMDYEfN7leiwXgWHW316Fq8YnOSjoPR6TPU=,tag:jdqqiBOZcOjygBMfKkrpNA==,type:str]
stringData:
  username: ENC[AES256_GCM,data:2VnceJRo8g9VMHmd8Q==,iv:mO4lJ0qu+X6Eq7g8DsQRssygP3S0IRxkxn4/YXT6I6o=,tag:o5uqRuL74XSCQGJnSXgNhA==,type:str]
  password: ENC[AES256_GCM,data:UREBh6ROKrnjVT3FvEsYKd7S7/rKvUPGoO8QbHZxVqA=,iv:iPkgFbXBcSEa0UqY5kY10zVlmUmHLwuGqJBUcuYdV4M=,tag:dMzHa9EHitoZ+Z7zW2a6Lw==,type:str]
  htpasswd: ENC[AES256_GCM,data:ODkFpNf4SvVyBplVtS+3Zh2/kLeDRAy+hpOiRzZp2D0eQQnqcc8K5lmc1BTGPK5PbuYZo7uc9Wbmg9ZFEs/YAA64wBLYBnTTY2hK,iv:1T9wHLC6FAU1xd6ppJqs8j98CuJHHlzucqd81niZjbg=,tag:FootppfeJ6my/9qVB3lmpA==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYzdzRDhZMSs0NU54ZFpv
        K2YwaDhaNStNS3B4dHF3M3lUUjVoS1BzQWhZCmNUQmh1cUVCOHNIVUJ4TDh2SW9t
        RUM4YzdRTEsza2NZbEpKQ2RMWlpaT0EKLS0tIDdBMEtlVXZIbDduQ2d2V3h4TEJL
        NTBTdldsNTdSUERRSUtzRnM0aXNMeWMKszYvy8/jWPJ18cWOQahlbpcLQK8V6BvW
        7LH3HQgmKeMvkIVbvlPt6/SKfeiZzNSxqiYe4XvFvXFPPmM90n9bcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T17:01:32Z"
  mac: ENC[AES256_GCM,data:uLBYCqzNWscY+wNB41ceca49TvBSJq/K+TdyG7z0bh4m/vsaZclM2UhVHisWZvQjpy3YC64lLfXGbbo3jcjQ2yu/tm16O4XpTmOPbgegpN+IAhh9/DheporCWq0QH4PSHrkGFMDaptz96Nv9Jgujh/AIC/Hd0a+YCDlD4KXMQfU=,iv:cmASEmjns5KIQBityG9McIVVglwgZu9KyW2Juz2RgZs=,tag:FNghfAwUFCN2kD4qKC6Vrg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
