apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: site-prod-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../secrets/site-config.prod.enc.yaml
  - ../../secrets/site-mysql.prod.enc.yaml
