apiVersion: ENC[AES256_GCM,data:0v4=,iv:9wU8oNc2ahbT7D0USBuCw9s/EmvUeupT/aVzjYIEe0U=,tag:tCe2CbXNWOMfN7V6hlJ9oA==,type:str]
kind: ENC[AES256_GCM,data:uaguq3CB,iv:RiJUupf6nHGU8qd04eOm4keDaCgU/NIA82wzZqQ32K4=,tag:AhdAA7Gvi0hmW5n08B/0eQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:qCCI5cKn66PCG91Lg6/3,iv:4B2KSsoWG7+NNRC3SJCdFyp7WC19reKYW0SbWkhDEko=,tag:tlurz0wM5fS3KIPf6wWjGQ==,type:str]
type: ENC[AES256_GCM,data:XgCl913k,iv:Pvswv5OMtv2MMEb5ReY5wLZ5VE7jy9RFH0RIF5+RH/U=,tag:dfV2kt0yVGoq9oFyrv0VDw==,type:str]
data:
  default: ENC[AES256_GCM,data:cV1RAoe4I8SGksKqpLxwke8QTajbAhqtJ9npvIt5GqYywO8YC+XIZmaMQ/scp1QbcBpp7NaOMHAD+teDCuVTdMVyYxZCyN5jcZxoE2Hl7Ni1YDVNXpzqYg==,iv:pLU3s6LxZJh8SwsMCen9+T00j16h6k6k5vPuYejRWXM=,tag:6yFwnDcdys2gCkXNDCQn4w==,type:str]
  external: ENC[AES256_GCM,data:P9Rz9KTKQWQtORot3C2UJxxJVuchePyevml/j3qjU3cYwEgF4VbUBhwcghDPnvpY2ZM8BQQFhWyH3ZSHZN6nfMsaHA2breS6cWIn9rAlhqlPoSD1u3lb1w==,iv:Nz4fQXy4oRvI6qluT+A7za9X6AVn+EHnbyfM0geNZy8=,tag:wR44gA8076z+st6nx7DXuQ==,type:str]
  externalAWG: ENC[AES256_GCM,data:wU8HKT959rBUp2Zo1zufpWgR005eCFcCKhq9aC/1FB3oQ8IkZQFNCGs1JbOcErvfVFf/6mOfCIBSz/JeuIKaTxQvH6uzpHRUb2+9sXFsvas=,iv:8qv1+tgN1l+oa8Z4AIIKXVNRrOtsspyX8npWBICWyqo=,tag:c9G8Oj6+VorZ6sVh954IRg==,type:str]
  internal: ENC[AES256_GCM,data:ySEG5sLzksXRhXYBf4EIFpoVyzRRWE5Lrv1jcuKvCBRbzxtnmz2qzJaeUwtP0XSRNtbfckOaemgspeGJawFEQeZUEEtMYnu74W/lLjxi9VCj7echWnrBfQ==,iv:Lrp9OkyndDhJP9dJvFiWbIaVIOPTIQfIUvqQtfl96Nk=,tag:25HoshKUUyh42sANl4aq+A==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEhKS1ZvMzdBcVVHL3dL
        ZS9VZzV0T1NpSmZaZGdRSmRLTjhUajhCR1Y4CmVXNmE0RkdleTYraGxuT2FDVURn
        ekNGUE9kOUE3TUZJRUZ4eUJ1cHZBUkEKLS0tIDhHQU5Va1E4R3M2dXd1dzd4OWJ3
        cTFZK2dEV1doSlM2YVgydm1keUNJRDgKjp6Hg+03IBuQa0sWs5qf3i75jYGMmOud
        G28Yq33vCarDVGAuqbxsP6wvyosEx8bKoQ1GnSWK/lo/GZTiHx0W8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T04:46:13Z"
  mac: ENC[AES256_GCM,data:DLCwGnGMuHrweYHrDXnX0FytFFa3GlwrCurd9L/+XwDbtq0GKwQ6w9DdXMIMz2zMFbE1Vaoavn1c0f+VvKV+Np1DTa6wlpDabw9H+eSfDFjYIgXdwU1VbgDzYJ3WrIuMs3PGHwvLp74g+quxdq+8ZrZ2naen+QF+c0ms2SqmDNg=,iv:FJjTl548zPkRloVKjqPFHI618CHMATRmQ1zJSkes5GE=,tag:viXAyn3ugkzAgHUDqwV4Ig==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
