apiVersion: ENC[AES256_GCM,data:vn4=,iv:KI4kS8BhV7Oqnof+sfxHg+g2WrjBkwGMK7qjUuWvNt4=,tag:SYYJydq8CjJ562sN2wvaqA==,type:str]
kind: ENC[AES256_GCM,data:NcIopByy,iv:60H4s7TrXlNQHVgoWCNJdz+M14xf1iH9czy/tfUyyBU=,tag:YoYs/TNa0kW7aAF/Rshn5w==,type:str]
metadata:
  name: ENC[AES256_GCM,data:MzWV4BGl+cfAx0uLqe4o,iv:Kuja+c/b9klta76238l+1TLeVu2gD9N2MQIW/jnCkKI=,tag:f8HIqACAg8XOwvLi3Z1s6g==,type:str]
type: ENC[AES256_GCM,data:M9bUQOgp,iv:KGpq2xR+DEqj2430SvKm3mLu6+laD6fI/OxabePJ2rM=,tag:jGtUvy+yN5TvDkEYRLLi7Q==,type:str]
data:
  default: ENC[AES256_GCM,data:W5PQ9qq0nBB3LuXWXaxBO44mvPBUioZ8khkEZdW3BoIaIw1o/ZSymPmsvXNyAm/w71ZDt/0lM4wwjrImL9FkaRO90sTLCFKm8TweSVFdUK4WRQLjHS+TvQ==,iv:zKS/JpWhFra9WESBi/TxUf3UKP6fZxyEQZVcL+2Y13c=,tag:3e4QZclosZu+Ptw8OSbz8w==,type:str]
  defaultAWG: ENC[AES256_GCM,data:vvgnhd2QDv3BEmnBZukEff/v91465GUXjtGfcPtOzVG7R3nqsu3+nbaguUNy7U+KjwTsLZsrc2IdU+0I9L2Xt8H308XgeK5bFR4W9/teyNI=,iv:Ve3Yn/jhvNqz1qqWJRtVcbSZLdjedEpwW3w7y2YEuOs=,tag:A8d8MYGcbQ8MxHjxLhQbhw==,type:str]
  external: ENC[AES256_GCM,data:okzG+0OWRTIQHCXIwvjKQMG18vKwIJCUW04HuHLJ8gX7TcpYGwnfT8Led3hyUCH7Z5YhXaTuf4YilU1xeO551S07qPwsHRRdJkiL2ToDh5GXG20FBLPykg==,iv:71G/zoUf6top/yVzEbW2acwqXzye4yzyIYmY1MwYDDA=,tag:oIilr7nKWgFS61fNonDukQ==,type:str]
  externalAWG: ENC[AES256_GCM,data:OY7W+9Xl2ZfZljksjzAvW1EZcozcbZnzKmAGgKZ5dp8dOGJMUYC5E/PlBdLg4KRVzxoH2zc9MFECQNsXon6kL9+ljl4uCl0mA1+fwvNaT5w=,iv:7kIXfRV3SremCcLYmyB28NGRruDc0FOjf8c0jp2beoc=,tag:eGMKECSroXdQCEi/R3SzYg==,type:str]
  internal: ENC[AES256_GCM,data:odHOhxmbwDOBftJLV7AzVlecz3iY8mhLeSi1MiXrHdLJv5ZPPY4JIzH/en2jwNFl3KOs5LNBmhrE+oTlAGviYj+uCWKR8RslSeSptli7IOM8JbHA+WgPQg==,iv:qaGuOxGMomidSFM11bltydXtrpvGu9+8GzaeEiyUKAI=,tag:yMmqfpIaNCVZT9mKY/bcQQ==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMmJOaXk5WUppV3lNVjF2
        WFplNTlkeHRUMk1Fc083RW14KzVVcFdOQ2hzCnMybXV4QzBxcWRoSGJ1RkxVVzZx
        c0w4ZmhwTTBxdU5tK0JQZDFNekRZSjAKLS0tIGFaTEp4SjgvNzVMZDdpcmJiQ1R5
        ci9PYzZZNXFEeXJkRjBtNVF1bVBjQzAKpfNy98xrWy/Li50c1mLS2pohIWIF2rmh
        BIolJPX4IJh5z+X8+aEn7jiLfK3NzZhAbLDhQE3RxhPJfIht+i0UtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T11:31:37Z"
  mac: ENC[AES256_GCM,data:r83Bip5dXLgi9N6hmnM61gvaPynRKBMi8+B27tdBg90fRIv1McX7OFrKf7cLYZB20aHjunUMiJaVpTf+JrTNDbumlA4PvB8Vgnt862YNpF+RXohxL5/dMw5bk31Zuc0GyMM+wNiQPLH+/cY0L4JFxmasRn030mFl6BSx+g3xVq0=,iv:s5IJPk2Tv+5UZ5iUB6YYVAlKG11pqyy4Hv025twRo3o=,tag:Nd1r6+cfqkPFgbvI8sXtKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
