apiVersion: ENC[AES256_GCM,data:ubE=,iv:V3gZC3pX5sy0rH6m6vvw7/uf8GtXUbInQ3BdhFpfNn0=,tag:pAiuQBriL5wKYfQVYKAMaQ==,type:str]
kind: ENC[AES256_GCM,data:lzSMMS+5,iv:giE/LLaBEQjaSNeltqYqFtdDDoJCIJl5i6HkWmNCmSo=,tag:9aOjgzvifMH3IWTTk1kVaA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:osGruer/qXY26rs6,iv:3Ml0RhyNzyCud2YMPL2hamDLQVQz8QIoDNCQQAc92SI=,tag:UNtFYYO9aB5F2yt2iKUtiA==,type:str]
data:
  mysql-root-password: ENC[AES256_GCM,data:l/1LfXn3cFI9K5+ZGa64/SIhXENkw6dN,iv:9VHWdyuHQA9wtVKvbMUU6Qni6OpXDbNXla+ztanYav0=,tag:Wuv3jbXsqxvc4UbfQ9Jx9g==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eUhOTjRVa3JLY1BDajla
        VFJPazNackxuVjFxUWllRnZ5eXU1UnoyNmdzClo0QmhFYzFzNkl5eUNwc1J6aXAy
        ZXJjRzZPdVp3K3NTcXdGN1crMVlpdEEKLS0tIFE3anJTZE9KUkozdDJQakFKOXd2
        bFZBdVh2UzFaSGRpV21idk9DWk5CQnMKfHt7FmZv96fmyxBAYqkx8EMMCUwqkX2F
        DFSNgPmB2pVKWEdqf0X6l+KvO04inbLHo9uF7rhJg9uDPiCM4Xv0Yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T17:21:29Z"
  mac: ENC[AES256_GCM,data:oYE03jf/lrhF8fNXUPMQd9uZeOZCdyAV54XdgCPjFOuPvIGTJlG4RyNAkxXmrafX/fSXddMF2rD5VBaqaioNSABvMnxZnykzWJMfSiaJOHromtv3R/HqqGBODcy7Da3gXghFRA523U5R7+gFsUrAlFxmJMIJyfosknWhfUfUl+w=,iv:NmnXRzQPN33VQx4nuX2EpQftFseTvf5FUzHLsywVA+c=,tag:VDaRhEHt+JdGXimb21FRgA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
