apiVersion: ENC[AES256_GCM,data:ox4=,iv:flETATYXPOeVs9AbE6BJ3UK+vgcdjZ6qm1Wuf8Ddd3I=,tag:BRQmYxwE+sQGEzZZBIekKQ==,type:str]
data:
  mysql-root-password: ENC[AES256_GCM,data:6mgZT+9q5q/Phh1Cw8cDgxwr0qA=,iv:RRk2yDzQgFb9PSVpSb/7vG8MC7CmztxGnbfTr9RaGoA=,tag:LYBjpQRZgjvO41TB3/qOLg==,type:str]
kind: ENC[AES256_GCM,data:aPMWsswh,iv:k+apKwokW/k+WKqCJ+6SS7Lzdu+zhxQuqz6x1M9rbNQ=,tag:i5SwxHjH9Abjn7OnKu3Swg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:N7l36g+wfommTlZL,iv:DiYAjMe0jYy4qf2Ull90hPdTLQzI+5j/tBJRcP/5ubw=,tag:+HXTaCDzHS3UUUhYF6kBIw==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cFE5dFFzS09JMmtOUVFU
        Rmg3ZEliMDdnR1pHS3dLUTVEVlZVNXhwem1FCjcyVnExelBYV2dHdnQ0ellweHU5
        Y0NJQ3Y0bHA1UHVDdTJ0SHEvaitGY2cKLS0tIDI5WnkrUU0vTUxoMVF0U05id1F2
        bWVzRjhacEIydk1XSXNUUU9EdFNCY0EKqFq8LGVANhIL+dY6rIOsQOZGvc33z5b1
        VGBbfYaD4VHmI7sGGG5VIVSiHlP1cxdYOi6uqo8MpFeWgpN4jiU10Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T19:29:25Z"
  mac: ENC[AES256_GCM,data:xKi7bD5qkgYPQvUkMnkyPG3Duov5CxX9ZNYj3ax7Y49rCaER26CtMmO7fSQVjpdVQD0Z0se9RZa/dWX+R4KIPmMZ0DYGQrdW+f2nlltMbd/WT4J0KpYpJo/ZO60dBIpb7zBOW2h6ya65GGDSA23SmRThLOQBk8ZEmWieiM5DhZ4=,iv:zgGcPNhEYBpMzivlKDh0vIca3fBj48DGmNngfnkZLTw=,tag:xvSo90rgf4xv6N5HHJZT7A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
