apiVersion: ENC[AES256_GCM,data:8ok=,iv:P5ltcETsDbgOaMbRAnow8hM1KmzPiTTp0/XCWsA+6TI=,tag:+xt7RAAEFQbVSCEXSpXQEg==,type:str]
kind: ENC[AES256_GCM,data:CSGsqk9F,iv:0bjZkua7ojmqW5OjwgdMXYYLHMJWCQ5glJcqOEw+8aM=,tag:KElUL4y2viE0S62YbubbcQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:nuEGYDS3N8azmMGH,iv:Mee+i0xL+WjyAa/wx99OcbPfh4J/e20kaGGO5UTwXws=,tag:zGLizjayvpad9mrzzIcP4A==,type:str]
data:
  mysql-root-password: ENC[AES256_GCM,data:GnricsWxZSXKIIHw2otOIJgq9F/1XJ5A,iv:7AT3sah7zGkgEKHb9MmsH1n62dn35dbAx74lswHWgNQ=,tag:t5LxHf/Rs8oOwqdPe+xthQ==,type:str]
sops:
  age:
    - recipient: age1rnfzyrzrlykyx2ak7jymfd6f4293e65kfchtgmrvuty6wl8dydeqqcnkg3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmJrenVBbTNVQ0t5czdh
        cVF0Z0MwYmJtT3RIdDBhY3RTakpqOU1XVm04CmFFTUlZSzhhL2UwTjlNdjdsaW14
        RkFLMmpLU3ZNa05mUmM3TXhscFM4bjgKLS0tIG91TDhlcVlNTDBRcmNHQitxSjQr
        QU55Z2VtRmRBeUZoWEZuVnFaelRDeTgKbp5NrnBq7TyZYEpQIUFz7rYd3QYDW2CX
        9R0urcKOkyTy270EuvyCZGeGCFb/ZC1UJBVxVnX/694KfWAXgVxHxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T20:28:41Z"
  mac: ENC[AES256_GCM,data:N/5ZqWqEZn2LF709Chx3+WM1fbkik9+rleM82MbiMvjhEEYobvO7xpkgaNLjasHebspB7goSpNRaMTDbdNu1q4L01Np8qc8+6m4btK7L0CVKI//5RDDZVt+MEXWM6DWW0uwJoHimoI8Y49YJ95XWuzLm+8GzhcvjgERfBO7JcD0=,iv:G7v8xbAZDREHzh/UEjD49H7RdNS8tRAq8/EFMMEqxD8=,tag:qMPuiIqbIJ+cS6a4xNRscA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
